# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20151224_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(blank=True, choices=[('tsp', 'teaspoons'), ('tbl', 'tablespoon'), ('cup', 'cup'), ('oz', 'ounce'), ('lb', 'pound'), ('dash', 'dash')], max_length=40, null=True),
        ),
    ]
