# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20151224_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
    ]
