# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20151224_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
