# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20151224_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(blank=True, choices=[('tsp', 'teaspoons'), ('tbl', 'tablespoons'), ('cup', 'cups'), ('oz', 'ounces'), ('lb', 'pounds'), ('dash', 'dash'), ('can', 'cans')], max_length=40, null=True),
        ),
    ]
