# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_auto_20151225_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(blank=True, choices=[('tsp', 'teaspoon'), ('tbl', 'tablespoon'), ('cup', 'cup'), ('oz', 'ounce'), ('lb', 'pound'), ('dash', 'dash'), ('can', 'can'), ('qt', 'quart')], max_length=40, null=True),
        ),
    ]
