# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0014_auto_20151225_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='alt_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
