# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_auto_20151225_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='book_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
