# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0017_auto_20151226_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_blob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
