# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0018_recipe_ingredients_blob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_blob',
            new_name='blob_ingredients',
        ),
    ]
