# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0019_auto_20151226_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves_upper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
