# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0020_auto_20151227_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
