# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0021_category_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='place',
        ),
    ]
