# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0022_remove_category_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='book_edition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
